name: Deploy to GitHub Pages

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn build
      - run: git config --global user.email "huylv177@gmail.com"
      - run: git config --global user.name "huy-lv"
      - run: git remote set-url origin https://huy-lv:${{ secrets.GH_PASSWORD }}@github.com/huy-lv/appwrite-cloner.git
      - run: yarn deploy